package com.nexa.risk_payment;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PaymentTemp1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int count;
	private java.lang.String transaction_type;

	private java.lang.String test;

	public PaymentTemp1() {
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public java.lang.String getTransaction_type() {
		return this.transaction_type;
	}

	public void setTransaction_type(java.lang.String transaction_type) {
		this.transaction_type = transaction_type;
	}

	public java.lang.String getTest() {
		return this.test;
	}

	public void setTest(java.lang.String test) {
		this.test = test;
	}

	public PaymentTemp1(int count, java.lang.String transaction_type,
			java.lang.String test) {
		this.count = count;
		this.transaction_type = transaction_type;
		this.test = test;
	}

}