package com.nexa.risk_payment;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PaymentTemp implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private double amount;
	private double tax;
	private double fee;

	public PaymentTemp() {
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public double getTax() {
		return this.tax;
	}

	public void setTax(double tax) {
		this.tax = tax;
	}

	public double getFee() {
		return this.fee;
	}

	public void setFee(double fee) {
		this.fee = fee;
	}

	public PaymentTemp(double amount, double tax, double fee) {
		this.amount = amount;
		this.tax = tax;
		this.fee = fee;
	}

}