package com.nexa.risk_payment;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PaymentTemp1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String transaction_type;

	private java.math.BigDecimal amount;

	private java.math.BigDecimal totalAmount;

	public PaymentTemp1() {
	}

	public java.lang.String getTransaction_type() {
		return this.transaction_type;
	}

	public void setTransaction_type(java.lang.String transaction_type) {
		this.transaction_type = transaction_type;
	}

	public java.math.BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(java.math.BigDecimal amount) {
		this.amount = amount;
	}

	public java.math.BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(java.math.BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	public PaymentTemp1(java.lang.String transaction_type,
			java.math.BigDecimal amount, java.math.BigDecimal totalAmount) {
		this.transaction_type = transaction_type;
		this.amount = amount;
		this.totalAmount = totalAmount;
	}

}