package com.nexa.risk_payment;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PaymentTemp1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int count;
	private java.lang.String transaction_type;

	private java.math.BigDecimal amount;

	private java.math.BigDecimal fee;

	private java.math.BigDecimal tax;

	public PaymentTemp1() {
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public java.lang.String getTransaction_type() {
		return this.transaction_type;
	}

	public void setTransaction_type(java.lang.String transaction_type) {
		this.transaction_type = transaction_type;
	}

	public java.math.BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(java.math.BigDecimal amount) {
		this.amount = amount;
	}

	public java.math.BigDecimal getFee() {
		return this.fee;
	}

	public void setFee(java.math.BigDecimal fee) {
		this.fee = fee;
	}

	public java.math.BigDecimal getTax() {
		return this.tax;
	}

	public void setTax(java.math.BigDecimal tax) {
		this.tax = tax;
	}

	public PaymentTemp1(int count, java.lang.String transaction_type,
			java.math.BigDecimal amount, java.math.BigDecimal fee,
			java.math.BigDecimal tax) {
		this.count = count;
		this.transaction_type = transaction_type;
		this.amount = amount;
		this.fee = fee;
		this.tax = tax;
	}

}