package com.nexa.risk_payment;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RiskResponseTemp implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String errorCode;
	private java.lang.String errorMessage;

	private int status;

	public RiskResponseTemp() {
	}

	public java.lang.String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(java.lang.String errorCode) {
		this.errorCode = errorCode;
	}

	public java.lang.String getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(java.lang.String errorMessage) {
		this.errorMessage = errorMessage;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public RiskResponseTemp(java.lang.String errorCode,
			java.lang.String errorMessage, int status) {
		this.errorCode = errorCode;
		this.errorMessage = errorMessage;
		this.status = status;
	}

}